export type SuperAdmin = {
  id: number;
  name: string;
  agent: string;
  promo_group: string;
  email: string;
  phone: string;
  status: boolean;
};

export const userSuperAdmin: SuperAdmin[] = [
  {
    id: 0,
    name: "Kelsey Horton",
    agent: "esensi digital",
    promo_group: "group_c",
    email: "kelseyhorton@geekus.com",
    phone: "+62 (825) 474-3988",
    status: true,
  },
  {
    id: 1,
    name: "Cabrera England",
    agent: "quavo",
    promo_group: "group_c",
    email: "cabreraengland@geekus.com",
    phone: "+62 (957) 478-2568",
    status: true,
  },
  {
    id: 2,
    name: "Kitty William",
    agent: "quavo",
    promo_group: "group_a",
    email: "kittywilliam@geekus.com",
    phone: "+62 (975) 533-3104",
    status: true,
  },
  {
    id: 3,
    name: "Maggie Velasquez",
    agent: "esensi digital",
    promo_group: "group_a",
    email: "maggievelasquez@geekus.com",
    phone: "+62 (825) 478-3914",
    status: true,
  },
  {
    id: 4,
    name: "Stefanie Salinas",
    agent: "esensi digital",
    promo_group: "group_a",
    email: "stefaniesalinas@geekus.com",
    phone: "+62 (808) 591-3546",
    status: true,
  },
  {
    id: 5,
    name: "Elaine Bass",
    agent: "vevo",
    promo_group: "group_c",
    email: "elainebass@geekus.com",
    phone: "+62 (899) 400-2525",
    status: true,
  },
  {
    id: 6,
    name: "William Britt",
    agent: "quavo",
    promo_group: "group_c",
    email: "williambritt@geekus.com",
    phone: "+62 (834) 470-3057",
    status: true,
  },
  {
    id: 7,
    name: "Harriett Garrett",
    agent: "quavo",
    promo_group: "group_b",
    email: "harriettgarrett@geekus.com",
    phone: "+62 (925) 544-2338",
    status: true,
  },
  {
    id: 8,
    name: "Delores Nielsen",
    agent: "quavo",
    promo_group: "group_b",
    email: "deloresnielsen@geekus.com",
    phone: "+62 (855) 532-2431",
    status: true,
  },
  {
    id: 9,
    name: "Lora Camacho",
    agent: "esensi digital",
    promo_group: "group_c",
    email: "loracamacho@geekus.com",
    phone: "+62 (804) 511-3186",
    status: true,
  },
  {
    id: 10,
    name: "Fleming Fitzpatrick",
    agent: "quavo",
    promo_group: "group_b",
    email: "flemingfitzpatrick@geekus.com",
    phone: "+62 (903) 425-3897",
    status: true,
  },
  {
    id: 11,
    name: "Cheri Vang",
    agent: "vevo",
    promo_group: "group_b",
    email: "cherivang@geekus.com",
    phone: "+62 (876) 548-2245",
    status: true,
  },
  {
    id: 12,
    name: "Grace Aguilar",
    agent: "vevo",
    promo_group: "group_a",
    email: "graceaguilar@geekus.com",
    phone: "+62 (867) 445-3930",
    status: true,
  },
  {
    id: 13,
    name: "Norman Humphrey",
    agent: "esensi digital",
    promo_group: "group_a",
    email: "normanhumphrey@geekus.com",
    phone: "+62 (947) 598-2919",
    status: true,
  },
  {
    id: 14,
    name: "Rasmussen Higgins",
    agent: "vevo",
    promo_group: "group_a",
    email: "rasmussenhiggins@geekus.com",
    phone: "+62 (825) 563-3277",
    status: true,
  },
  {
    id: 15,
    name: "Schwartz Mullen",
    agent: "vevo",
    promo_group: "group_c",
    email: "schwartzmullen@geekus.com",
    phone: "+62 (898) 439-3581",
    status: true,
  },
  {
    id: 16,
    name: "Guy Norton",
    agent: "esensi digital",
    promo_group: "group_b",
    email: "guynorton@geekus.com",
    phone: "+62 (991) 517-2026",
    status: true,
  },
  {
    id: 17,
    name: "Roth Fuller",
    agent: "vevo",
    promo_group: "group_c",
    email: "rothfuller@geekus.com",
    phone: "+62 (828) 488-2654",
    status: true,
  },
  {
    id: 18,
    name: "Austin Gilmore",
    agent: "vevo",
    promo_group: "group_c",
    email: "austingilmore@geekus.com",
    phone: "+62 (943) 512-2110",
    status: true,
  },
  {
    id: 19,
    name: "Trudy Adams",
    agent: "esensi digital",
    promo_group: "group_c",
    email: "trudyadams@geekus.com",
    phone: "+62 (882) 534-3609",
    status: true,
  },
  {
    id: 20,
    name: "Lilian Cotton",
    agent: "vevo",
    promo_group: "group_b",
    email: "liliancotton@geekus.com",
    phone: "+62 (935) 444-2039",
    status: true,
  },
  {
    id: 21,
    name: "Dana Forbes",
    agent: "vevo",
    promo_group: "group_c",
    email: "danaforbes@geekus.com",
    phone: "+62 (931) 492-2632",
    status: true,
  },
  {
    id: 22,
    name: "Larsen Wilkins",
    agent: "quavo",
    promo_group: "group_b",
    email: "larsenwilkins@geekus.com",
    phone: "+62 (830) 521-3203",
    status: true,
  },
  {
    id: 23,
    name: "Elma Peterson",
    agent: "esensi digital",
    promo_group: "group_c",
    email: "elmapeterson@geekus.com",
    phone: "+62 (857) 503-2327",
    status: true,
  },
  {
    id: 24,
    name: "Britt Graves",
    agent: "quavo",
    promo_group: "group_b",
    email: "brittgraves@geekus.com",
    phone: "+62 (891) 403-2172",
    status: true,
  },
  {
    id: 25,
    name: "Christina Castaneda",
    agent: "vevo",
    promo_group: "group_c",
    email: "christinacastaneda@geekus.com",
    phone: "+62 (893) 568-2246",
    status: true,
  },
  {
    id: 26,
    name: "Rice Cline",
    agent: "vevo",
    promo_group: "group_b",
    email: "ricecline@geekus.com",
    phone: "+62 (869) 466-2233",
    status: true,
  },
  {
    id: 27,
    name: "Rocha Bond",
    agent: "vevo",
    promo_group: "group_c",
    email: "rochabond@geekus.com",
    phone: "+62 (907) 465-3503",
    status: true,
  },
  {
    id: 28,
    name: "Eve Goodman",
    agent: "quavo",
    promo_group: "group_a",
    email: "evegoodman@geekus.com",
    phone: "+62 (846) 459-2731",
    status: true,
  },
  {
    id: 29,
    name: "Lea Banks",
    agent: "quavo",
    promo_group: "group_b",
    email: "leabanks@geekus.com",
    phone: "+62 (878) 525-2810",
    status: true,
  },
  {
    id: 30,
    name: "Solomon Ware",
    agent: "quavo",
    promo_group: "group_c",
    email: "solomonware@geekus.com",
    phone: "+62 (885) 590-3847",
    status: true,
  },
  {
    id: 31,
    name: "Alba Nelson",
    agent: "vevo",
    promo_group: "group_b",
    email: "albanelson@geekus.com",
    phone: "+62 (893) 528-3311",
    status: true,
  },
  {
    id: 32,
    name: "Walton Stanton",
    agent: "vevo",
    promo_group: "group_a",
    email: "waltonstanton@geekus.com",
    phone: "+62 (856) 416-3700",
    status: true,
  },
  {
    id: 33,
    name: "Kramer Tyson",
    agent: "quavo",
    promo_group: "group_c",
    email: "kramertyson@geekus.com",
    phone: "+62 (830) 486-2980",
    status: true,
  },
  {
    id: 34,
    name: "Lilly Mcknight",
    agent: "esensi digital",
    promo_group: "group_a",
    email: "lillymcknight@geekus.com",
    phone: "+62 (882) 550-2950",
    status: true,
  },
  {
    id: 35,
    name: "Bullock Terry",
    agent: "quavo",
    promo_group: "group_b",
    email: "bullockterry@geekus.com",
    phone: "+62 (817) 594-3754",
    status: true,
  },
  {
    id: 36,
    name: "Frieda Hensley",
    agent: "esensi digital",
    promo_group: "group_b",
    email: "friedahensley@geekus.com",
    phone: "+62 (919) 438-3050",
    status: true,
  },
  {
    id: 37,
    name: "Yesenia Hyde",
    agent: "quavo",
    promo_group: "group_a",
    email: "yeseniahyde@geekus.com",
    phone: "+62 (844) 419-2711",
    status: true,
  },
  {
    id: 38,
    name: "Blanca Pierce",
    agent: "quavo",
    promo_group: "group_b",
    email: "blancapierce@geekus.com",
    phone: "+62 (984) 549-2398",
    status: true,
  },
  {
    id: 39,
    name: "Isabel Alvarado",
    agent: "esensi digital",
    promo_group: "group_c",
    email: "isabelalvarado@geekus.com",
    phone: "+62 (920) 454-3703",
    status: true,
  },
  {
    id: 40,
    name: "Mclaughlin Ball",
    agent: "quavo",
    promo_group: "group_b",
    email: "mclaughlinball@geekus.com",
    phone: "+62 (895) 582-3113",
    status: true,
  },
  {
    id: 41,
    name: "Herminia Hood",
    agent: "esensi digital",
    promo_group: "group_a",
    email: "herminiahood@geekus.com",
    phone: "+62 (866) 425-3730",
    status: true,
  },
  {
    id: 42,
    name: "Dunlap Downs",
    agent: "quavo",
    promo_group: "group_c",
    email: "dunlapdowns@geekus.com",
    phone: "+62 (819) 563-2930",
    status: true,
  },
  {
    id: 43,
    name: "Cobb Stevenson",
    agent: "esensi digital",
    promo_group: "group_a",
    email: "cobbstevenson@geekus.com",
    phone: "+62 (978) 548-2324",
    status: true,
  },
  {
    id: 44,
    name: "Alyce Velazquez",
    agent: "esensi digital",
    promo_group: "group_c",
    email: "alycevelazquez@geekus.com",
    phone: "+62 (971) 486-3357",
    status: true,
  },
  {
    id: 45,
    name: "Zelma Johnson",
    agent: "vevo",
    promo_group: "group_c",
    email: "zelmajohnson@geekus.com",
    phone: "+62 (893) 436-2500",
    status: true,
  },
  {
    id: 46,
    name: "Chavez Delacruz",
    agent: "esensi digital",
    promo_group: "group_c",
    email: "chavezdelacruz@geekus.com",
    phone: "+62 (810) 414-3117",
    status: true,
  },
  {
    id: 47,
    name: "Susan Russell",
    agent: "vevo",
    promo_group: "group_b",
    email: "susanrussell@geekus.com",
    phone: "+62 (817) 490-2564",
    status: true,
  },
  {
    id: 48,
    name: "Kay Buckner",
    agent: "vevo",
    promo_group: "group_a",
    email: "kaybuckner@geekus.com",
    phone: "+62 (899) 412-3353",
    status: true,
  },
  {
    id: 49,
    name: "Nannie Todd",
    agent: "quavo",
    promo_group: "group_a",
    email: "nannietodd@geekus.com",
    phone: "+62 (826) 449-3133",
    status: true,
  },
  {
    id: 50,
    name: "Carlene Davidson",
    agent: "esensi digital",
    promo_group: "group_b",
    email: "carlenedavidson@geekus.com",
    phone: "+62 (886) 451-3424",
    status: true,
  },
  {
    id: 51,
    name: "Enid Medina",
    agent: "vevo",
    promo_group: "group_a",
    email: "enidmedina@geekus.com",
    phone: "+62 (819) 466-2989",
    status: true,
  },
  {
    id: 52,
    name: "Mendez Vaughan",
    agent: "quavo",
    promo_group: "group_c",
    email: "mendezvaughan@geekus.com",
    phone: "+62 (903) 502-2260",
    status: true,
  },
  {
    id: 53,
    name: "Weaver Hoffman",
    agent: "vevo",
    promo_group: "group_a",
    email: "weaverhoffman@geekus.com",
    phone: "+62 (840) 456-2091",
    status: true,
  },
  {
    id: 54,
    name: "Todd Guthrie",
    agent: "esensi digital",
    promo_group: "group_b",
    email: "toddguthrie@geekus.com",
    phone: "+62 (827) 571-3834",
    status: true,
  },
  {
    id: 55,
    name: "Langley Blackwell",
    agent: "quavo",
    promo_group: "group_a",
    email: "langleyblackwell@geekus.com",
    phone: "+62 (946) 413-2660",
    status: true,
  },
  {
    id: 56,
    name: "Merrill Farmer",
    agent: "esensi digital",
    promo_group: "group_b",
    email: "merrillfarmer@geekus.com",
    phone: "+62 (953) 596-2164",
    status: true,
  },
  {
    id: 57,
    name: "Shana Rose",
    agent: "esensi digital",
    promo_group: "group_b",
    email: "shanarose@geekus.com",
    phone: "+62 (852) 464-2279",
    status: true,
  },
  {
    id: 58,
    name: "Gilbert Cruz",
    agent: "quavo",
    promo_group: "group_b",
    email: "gilbertcruz@geekus.com",
    phone: "+62 (896) 564-2613",
    status: true,
  },
  {
    id: 59,
    name: "Lawrence Bowen",
    agent: "quavo",
    promo_group: "group_a",
    email: "lawrencebowen@geekus.com",
    phone: "+62 (968) 496-3742",
    status: true,
  },
  {
    id: 60,
    name: "Earlene Munoz",
    agent: "esensi digital",
    promo_group: "group_c",
    email: "earlenemunoz@geekus.com",
    phone: "+62 (897) 523-3201",
    status: true,
  },
  {
    id: 61,
    name: "Diann Joyner",
    agent: "vevo",
    promo_group: "group_b",
    email: "diannjoyner@geekus.com",
    phone: "+62 (977) 488-2320",
    status: true,
  },
  {
    id: 62,
    name: "Harriet Vincent",
    agent: "esensi digital",
    promo_group: "group_a",
    email: "harrietvincent@geekus.com",
    phone: "+62 (904) 442-2222",
    status: true,
  },
  {
    id: 63,
    name: "Jenifer Dejesus",
    agent: "esensi digital",
    promo_group: "group_b",
    email: "jeniferdejesus@geekus.com",
    phone: "+62 (845) 570-2222",
    status: true,
  },
  {
    id: 64,
    name: "Margie Fisher",
    agent: "esensi digital",
    promo_group: "group_c",
    email: "margiefisher@geekus.com",
    phone: "+62 (900) 485-2463",
    status: true,
  },
  {
    id: 65,
    name: "Madelyn Weber",
    agent: "esensi digital",
    promo_group: "group_a",
    email: "madelynweber@geekus.com",
    phone: "+62 (910) 549-2164",
    status: true,
  },
  {
    id: 66,
    name: "Marta Lang",
    agent: "quavo",
    promo_group: "group_b",
    email: "martalang@geekus.com",
    phone: "+62 (978) 447-3854",
    status: true,
  },
  {
    id: 67,
    name: "Virgie Miles",
    agent: "esensi digital",
    promo_group: "group_c",
    email: "virgiemiles@geekus.com",
    phone: "+62 (899) 497-2213",
    status: true,
  },
];
